version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: wp_nginx
    volumes:
      - ./wp/var-www-wp:/var/www/wp
    ports:
      - "8000:80"
    links:
      - wp
  wp:
    build:
      context: ./wp
      dockerfile: Dockerfile
    container_name: wp_wp
    env_file: development.env
    volumes:
      - ./wp/var-www-wp:/var/www/wp
    links:
      - mysql
  mysql:
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: wp_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: development.env
    ports:
      - "3306:3306"